### ISSUE TITLE
Add Default Filters

### ISSUE THREAD

**Issue by MadeofTin** [Giveth/ethereum-signal-aggregator#6]
On load certain filters should be enabled by default.

Status : Draft, Last Call , Accepted
Category : All

![image](https://user-images.githubusercontent.com/1226869/44848140-aeb91c80-ac23-11e8-8b80-69f86ed2dfe5.png)

**Comment by deamme** [comment]
Fixed in https://github.com/Giveth/ethereum-signal-aggregator/commit/137541f0f0afaef67a132ea0bb94e55e72df2296
